// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package sqlc

import (
	"context"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(1) FROM projects
WHERE (COALESCE(?1, '') = '' OR name LIKE ?1)
AND (COALESCE(?2, '') = '' OR creator LIKE ?2)
`

type CountProjectsParams struct {
	Name    interface{}
	Creator interface{}
}

func (q *Queries) CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects, arg.Name, arg.Creator)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, creator, updated_at FROM projects WHERE id = ?1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Creator,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectDetailByID = `-- name: GetProjectDetailByID :many
SELECT projects.name AS project_name,
	projects.id AS project_id,
	projects.creator AS project_creator,
	projects.updated_at AS project_updated_at,
	devices.name AS device_name,
	devices."order" AS device_order,
	participants.name AS participant_name,
	participants.serial AS participant_serial,
	winfitts_information.id AS information_id,
	winfitts_information.deleted,
	winfitts_information.error_times,
	winfitts_information.is_failed,
	winfitts_information.trail_number,
	winfitts_information.width,
	winfitts_information.distance,
	winfitts_details.mark,
	winfitts_details.timestamp,
	winfitts_details.x,
	winfitts_details.y
FROM projects
INNER JOIN devices ON projects.id = devices.project_id
INNER JOIN participants ON projects.id  = participants.project_id
INNER JOIN winfitts ON
	projects.id = winfitts.project_id
	AND devices.id = winfitts.device_id
	AND participants.id = winfitts.participant_id
INNER JOIN winfitts_information ON winfitts.id = winfitts_information.winfitts_id
INNER JOIN winfitts_details ON winfitts_information.id = winfitts_details.information_id
WHERE projects.id = ?1
ORDER BY device_name, participant_name, trail_number ASC
`

type GetProjectDetailByIDRow struct {
	ProjectName       string
	ProjectID         string
	ProjectCreator    string
	ProjectUpdatedAt  string
	DeviceName        string
	DeviceOrder       string
	ParticipantName   string
	ParticipantSerial string
	InformationID     string
	Deleted           bool
	ErrorTimes        int64
	IsFailed          bool
	TrailNumber       int64
	Width             int64
	Distance          int64
	Mark              string
	Timestamp         int64
	X                 int64
	Y                 int64
}

func (q *Queries) GetProjectDetailByID(ctx context.Context, projectID string) ([]GetProjectDetailByIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getProjectDetailByID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectDetailByIDRow
	for rows.Next() {
		var i GetProjectDetailByIDRow
		if err := rows.Scan(
			&i.ProjectName,
			&i.ProjectID,
			&i.ProjectCreator,
			&i.ProjectUpdatedAt,
			&i.DeviceName,
			&i.DeviceOrder,
			&i.ParticipantName,
			&i.ParticipantSerial,
			&i.InformationID,
			&i.Deleted,
			&i.ErrorTimes,
			&i.IsFailed,
			&i.TrailNumber,
			&i.Width,
			&i.Distance,
			&i.Mark,
			&i.Timestamp,
			&i.X,
			&i.Y,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsOrderByCreatorAsc = `-- name: ListProjectsOrderByCreatorAsc :many
SELECT id, name, creator, updated_at FROM projects
WHERE (COALESCE(?1, '') = '' OR name LIKE ?1)
AND (COALESCE(?2, '') = '' OR creator LIKE ?2)
ORDER BY creator ASC, updated_at DESC
LIMIT ?4 OFFSET ?3
`

type ListProjectsOrderByCreatorAscParams struct {
	Name    interface{}
	Creator interface{}
	Offset  int64
	Limit   int64
}

func (q *Queries) ListProjectsOrderByCreatorAsc(ctx context.Context, arg ListProjectsOrderByCreatorAscParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsOrderByCreatorAsc,
		arg.Name,
		arg.Creator,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Creator,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsOrderByCreatorDesc = `-- name: ListProjectsOrderByCreatorDesc :many
SELECT id, name, creator, updated_at FROM projects
WHERE (COALESCE(?1, '') = '' OR name LIKE ?1)
AND (COALESCE(?2, '') = '' OR creator LIKE ?2)
ORDER BY creator DESC, updated_at DESC
LIMIT ?4 OFFSET ?3
`

type ListProjectsOrderByCreatorDescParams struct {
	Name    interface{}
	Creator interface{}
	Offset  int64
	Limit   int64
}

func (q *Queries) ListProjectsOrderByCreatorDesc(ctx context.Context, arg ListProjectsOrderByCreatorDescParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsOrderByCreatorDesc,
		arg.Name,
		arg.Creator,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Creator,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsOrderByNameAsc = `-- name: ListProjectsOrderByNameAsc :many
SELECT id, name, creator, updated_at FROM projects
WHERE (COALESCE(?1, '') = '' OR name LIKE ?1)
AND (COALESCE(?2, '') = '' OR creator LIKE ?2)
ORDER BY name ASC, updated_at DESC
LIMIT ?4 OFFSET ?3
`

type ListProjectsOrderByNameAscParams struct {
	Name    interface{}
	Creator interface{}
	Offset  int64
	Limit   int64
}

func (q *Queries) ListProjectsOrderByNameAsc(ctx context.Context, arg ListProjectsOrderByNameAscParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsOrderByNameAsc,
		arg.Name,
		arg.Creator,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Creator,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsOrderByNameDesc = `-- name: ListProjectsOrderByNameDesc :many
SELECT id, name, creator, updated_at FROM projects
WHERE (COALESCE(?1, '') = '' OR name LIKE ?1)
AND (COALESCE(?2, '') = '' OR creator LIKE ?2)
ORDER BY name DESC, updated_at DESC
LIMIT ?4 OFFSET ?3
`

type ListProjectsOrderByNameDescParams struct {
	Name    interface{}
	Creator interface{}
	Offset  int64
	Limit   int64
}

func (q *Queries) ListProjectsOrderByNameDesc(ctx context.Context, arg ListProjectsOrderByNameDescParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsOrderByNameDesc,
		arg.Name,
		arg.Creator,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Creator,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsOrderByUpdatedAtAsc = `-- name: ListProjectsOrderByUpdatedAtAsc :many
SELECT id, name, creator, updated_at FROM projects
WHERE (COALESCE(?1, '') = '' OR name LIKE ?1)
AND (COALESCE(?2, '') = '' OR creator LIKE ?2)
ORDER BY updated_at ASC
LIMIT ?4 OFFSET ?3
`

type ListProjectsOrderByUpdatedAtAscParams struct {
	Name    interface{}
	Creator interface{}
	Offset  int64
	Limit   int64
}

func (q *Queries) ListProjectsOrderByUpdatedAtAsc(ctx context.Context, arg ListProjectsOrderByUpdatedAtAscParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsOrderByUpdatedAtAsc,
		arg.Name,
		arg.Creator,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Creator,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsOrderByUpdatedAtDesc = `-- name: ListProjectsOrderByUpdatedAtDesc :many
SELECT id, name, creator, updated_at FROM projects
WHERE (COALESCE(?1, '') = '' OR name LIKE ?1)
AND (COALESCE(?2, '') = '' OR creator LIKE ?2)
ORDER BY updated_at DESC
LIMIT ?4 OFFSET ?3
`

type ListProjectsOrderByUpdatedAtDescParams struct {
	Name    interface{}
	Creator interface{}
	Offset  int64
	Limit   int64
}

func (q *Queries) ListProjectsOrderByUpdatedAtDesc(ctx context.Context, arg ListProjectsOrderByUpdatedAtDescParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsOrderByUpdatedAtDesc,
		arg.Name,
		arg.Creator,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Creator,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (id, name, creator, updated_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(id) DO UPDATE SET
    name = EXCLUDED.name,
    creator = EXCLUDED.creator,
    updated_at = EXCLUDED.updated_at
RETURNING id, name, creator, updated_at
`

type UpsertProjectParams struct {
	ID        string
	Name      string
	Creator   string
	UpdatedAt string
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, upsertProject,
		arg.ID,
		arg.Name,
		arg.Creator,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Creator,
		&i.UpdatedAt,
	)
	return i, err
}
