// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sqlc

import (
	"context"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(1) FROM projects
WHERE (COALESCE(?1, '') = '' OR name LIKE ?1)
AND (COALESCE(?2, '') = '' OR creator LIKE ?2)
`

type CountProjectsParams struct {
	Name    interface{}
	Creator interface{}
}

func (q *Queries) CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects, arg.Name, arg.Creator)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findProject = `-- name: FindProject :one
SELECT id, name, creator, updated_at FROM projects WHERE id = ?1
`

func (q *Queries) FindProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, findProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Creator,
		&i.UpdatedAt,
	)
	return i, err
}

const findProjectDetails = `-- name: FindProjectDetails :many
SELECT projects.name AS project_name,
	projects.id AS project_id,
	projects.creator AS project_creator,
	projects.updated_at AS project_updated_at,
	devices.name AS device_name,
	devices."order" AS device_order,
	participants.name AS participant_name,
	participants.serial AS participant_serial,
	winfitts_information.id AS information_id,
	winfitts_information.deleted,
	winfitts_information.error_times,
	winfitts_information.is_failed,
	winfitts_information.trail_number,
	winfitts_information.width,
	winfitts_information.distance,
	winfitts_details.mark,
	winfitts_details.timestamp,
	winfitts_details.x,
	winfitts_details.y
FROM projects
INNER JOIN devices ON projects.id = devices.project_id
INNER JOIN participants ON projects.id  = participants.project_id
INNER JOIN winfitts ON
	projects.id = winfitts.project_id
	AND devices.id = winfitts.device_id
	AND participants.id = winfitts.participant_id
INNER JOIN winfitts_information ON winfitts.id = winfitts_information.winfitts_id
INNER JOIN winfitts_details ON winfitts_information.id = winfitts_details.information_id
WHERE projects.id = ?1
ORDER BY device_name, participant_name, trail_number ASC
`

type FindProjectDetailsRow struct {
	ProjectName       string
	ProjectID         string
	ProjectCreator    string
	ProjectUpdatedAt  string
	DeviceName        string
	DeviceOrder       string
	ParticipantName   string
	ParticipantSerial string
	InformationID     string
	Deleted           bool
	ErrorTimes        int64
	IsFailed          bool
	TrailNumber       int64
	Width             int64
	Distance          int64
	Mark              string
	Timestamp         int64
	X                 int64
	Y                 int64
}

func (q *Queries) FindProjectDetails(ctx context.Context, projectID string) ([]FindProjectDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, findProjectDetails, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindProjectDetailsRow
	for rows.Next() {
		var i FindProjectDetailsRow
		if err := rows.Scan(
			&i.ProjectName,
			&i.ProjectID,
			&i.ProjectCreator,
			&i.ProjectUpdatedAt,
			&i.DeviceName,
			&i.DeviceOrder,
			&i.ParticipantName,
			&i.ParticipantSerial,
			&i.InformationID,
			&i.Deleted,
			&i.ErrorTimes,
			&i.IsFailed,
			&i.TrailNumber,
			&i.Width,
			&i.Distance,
			&i.Mark,
			&i.Timestamp,
			&i.X,
			&i.Y,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByCreatorAsc = `-- name: ListProjectsByCreatorAsc :many
SELECT id, name, creator, updated_at FROM projects
WHERE (COALESCE(?1, '') = '' OR name LIKE ?1)
AND (COALESCE(?2, '') = '' OR creator LIKE ?2)
ORDER BY creator ASC, updated_at DESC
LIMIT ?4 OFFSET ?3
`

type ListProjectsByCreatorAscParams struct {
	Name    interface{}
	Creator interface{}
	Offset  int64
	Limit   int64
}

func (q *Queries) ListProjectsByCreatorAsc(ctx context.Context, arg ListProjectsByCreatorAscParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByCreatorAsc,
		arg.Name,
		arg.Creator,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Creator,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByCreatorDesc = `-- name: ListProjectsByCreatorDesc :many
SELECT id, name, creator, updated_at FROM projects
WHERE (COALESCE(?1, '') = '' OR name LIKE ?1)
AND (COALESCE(?2, '') = '' OR creator LIKE ?2)
ORDER BY creator DESC, updated_at DESC
LIMIT ?4 OFFSET ?3
`

type ListProjectsByCreatorDescParams struct {
	Name    interface{}
	Creator interface{}
	Offset  int64
	Limit   int64
}

func (q *Queries) ListProjectsByCreatorDesc(ctx context.Context, arg ListProjectsByCreatorDescParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByCreatorDesc,
		arg.Name,
		arg.Creator,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Creator,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByNameAsc = `-- name: ListProjectsByNameAsc :many
SELECT id, name, creator, updated_at FROM projects
WHERE (COALESCE(?1, '') = '' OR name LIKE ?1)
AND (COALESCE(?2, '') = '' OR creator LIKE ?2)
ORDER BY name ASC, updated_at DESC
LIMIT ?4 OFFSET ?3
`

type ListProjectsByNameAscParams struct {
	Name    interface{}
	Creator interface{}
	Offset  int64
	Limit   int64
}

func (q *Queries) ListProjectsByNameAsc(ctx context.Context, arg ListProjectsByNameAscParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByNameAsc,
		arg.Name,
		arg.Creator,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Creator,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByNameDesc = `-- name: ListProjectsByNameDesc :many
SELECT id, name, creator, updated_at FROM projects
WHERE (COALESCE(?1, '') = '' OR name LIKE ?1)
AND (COALESCE(?2, '') = '' OR creator LIKE ?2)
ORDER BY name DESC, updated_at DESC
LIMIT ?4 OFFSET ?3
`

type ListProjectsByNameDescParams struct {
	Name    interface{}
	Creator interface{}
	Offset  int64
	Limit   int64
}

func (q *Queries) ListProjectsByNameDesc(ctx context.Context, arg ListProjectsByNameDescParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByNameDesc,
		arg.Name,
		arg.Creator,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Creator,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByTimeAsc = `-- name: ListProjectsByTimeAsc :many
SELECT id, name, creator, updated_at FROM projects
WHERE (COALESCE(?1, '') = '' OR name LIKE ?1)
AND (COALESCE(?2, '') = '' OR creator LIKE ?2)
ORDER BY updated_at ASC
LIMIT ?4 OFFSET ?3
`

type ListProjectsByTimeAscParams struct {
	Name    interface{}
	Creator interface{}
	Offset  int64
	Limit   int64
}

func (q *Queries) ListProjectsByTimeAsc(ctx context.Context, arg ListProjectsByTimeAscParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByTimeAsc,
		arg.Name,
		arg.Creator,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Creator,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByTimeDesc = `-- name: ListProjectsByTimeDesc :many
SELECT id, name, creator, updated_at FROM projects
WHERE (COALESCE(?1, '') = '' OR name LIKE ?1)
AND (COALESCE(?2, '') = '' OR creator LIKE ?2)
ORDER BY updated_at DESC
LIMIT ?4 OFFSET ?3
`

type ListProjectsByTimeDescParams struct {
	Name    interface{}
	Creator interface{}
	Offset  int64
	Limit   int64
}

func (q *Queries) ListProjectsByTimeDesc(ctx context.Context, arg ListProjectsByTimeDescParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByTimeDesc,
		arg.Name,
		arg.Creator,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Creator,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
