// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sqlc

import (
	"context"
)

const upsertDevices = `-- name: UpsertDevices :one
INSERT INTO devices (id, name, project_id)
VALUES (?1, ?2, ?3)
ON CONFLICT(name, project_id) DO UPDATE
    SET name = EXCLUDED.name
RETURNING id, name, project_id
`

type UpsertDevicesParams struct {
	ID        string
	Name      string
	ProjectID string
}

func (q *Queries) UpsertDevices(ctx context.Context, arg UpsertDevicesParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, upsertDevices, arg.ID, arg.Name, arg.ProjectID)
	var i Device
	err := row.Scan(&i.ID, &i.Name, &i.ProjectID)
	return i, err
}

const upsertParticipants = `-- name: UpsertParticipants :one
INSERT INTO participants (id, name, project_id, serial)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(name, project_id) DO UPDATE
    SET name = EXCLUDED.name
RETURNING id, serial, name, project_id
`

type UpsertParticipantsParams struct {
	ID        string
	Name      string
	ProjectID string
	Serial    string
}

func (q *Queries) UpsertParticipants(ctx context.Context, arg UpsertParticipantsParams) (Participant, error) {
	row := q.db.QueryRowContext(ctx, upsertParticipants,
		arg.ID,
		arg.Name,
		arg.ProjectID,
		arg.Serial,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Serial,
		&i.Name,
		&i.ProjectID,
	)
	return i, err
}

const upsertWinfitts = `-- name: UpsertWinfitts :one
INSERT INTO winfitts (id, project_id, device_id, participant_id)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(project_id, device_id, participant_id) DO UPDATE
    SET device_id = EXCLUDED.device_id
RETURNING id, project_id, device_id, participant_id, "foreign"
`

type UpsertWinfittsParams struct {
	ID            string
	ProjectID     string
	DeviceID      string
	ParticipantID string
}

func (q *Queries) UpsertWinfitts(ctx context.Context, arg UpsertWinfittsParams) (Winfitt, error) {
	row := q.db.QueryRowContext(ctx, upsertWinfitts,
		arg.ID,
		arg.ProjectID,
		arg.DeviceID,
		arg.ParticipantID,
	)
	var i Winfitt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DeviceID,
		&i.ParticipantID,
		&i.Foreign,
	)
	return i, err
}

const upsertWinfittsDetail = `-- name: UpsertWinfittsDetail :one
INSERT INTO winfitts_details (id, information_id, mark, x, y, timestamp)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT(information_id, timestamp) DO UPDATE
    SET timestamp = EXCLUDED.timestamp
RETURNING id, information_id, mark, x, y, timestamp
`

type UpsertWinfittsDetailParams struct {
	ID            string
	InformationID string
	Mark          string
	X             int64
	Y             int64
	Timestamp     int64
}

func (q *Queries) UpsertWinfittsDetail(ctx context.Context, arg UpsertWinfittsDetailParams) (WinfittsDetail, error) {
	row := q.db.QueryRowContext(ctx, upsertWinfittsDetail,
		arg.ID,
		arg.InformationID,
		arg.Mark,
		arg.X,
		arg.Y,
		arg.Timestamp,
	)
	var i WinfittsDetail
	err := row.Scan(
		&i.ID,
		&i.InformationID,
		&i.Mark,
		&i.X,
		&i.Y,
		&i.Timestamp,
	)
	return i, err
}

const upsertWinfittsInformation = `-- name: UpsertWinfittsInformation :one
INSERT INTO winfitts_information (id, winfitts_id, trail_number, width, distance, angle, is_failed, error_times, deleted, reason)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
ON CONFLICT(winfitts_id, trail_number) DO UPDATE
    SET is_failed = EXCLUDED.is_failed,
    error_times = EXCLUDED.error_times,
    deleted = EXCLUDED.deleted,
    reason = EXCLUDED.reason
RETURNING id, winfitts_id, trail_number, width, distance, angle, is_failed, error_times, deleted, reason
`

type UpsertWinfittsInformationParams struct {
	ID          string
	WinfittsID  string
	TrailNumber int64
	Width       int64
	Distance    int64
	Angle       int64
	IsFailed    bool
	ErrorTimes  int64
	Deleted     bool
	Reason      string
}

func (q *Queries) UpsertWinfittsInformation(ctx context.Context, arg UpsertWinfittsInformationParams) (WinfittsInformation, error) {
	row := q.db.QueryRowContext(ctx, upsertWinfittsInformation,
		arg.ID,
		arg.WinfittsID,
		arg.TrailNumber,
		arg.Width,
		arg.Distance,
		arg.Angle,
		arg.IsFailed,
		arg.ErrorTimes,
		arg.Deleted,
		arg.Reason,
	)
	var i WinfittsInformation
	err := row.Scan(
		&i.ID,
		&i.WinfittsID,
		&i.TrailNumber,
		&i.Width,
		&i.Distance,
		&i.Angle,
		&i.IsFailed,
		&i.ErrorTimes,
		&i.Deleted,
		&i.Reason,
	)
	return i, err
}
