version: "2"
run:
  concurrency: 2
  go: "1.24"
  tests: true
linters:
  default: all
  disable:
    - contextcheck
    - depguard
    - exhaustruct
    - gomodguard
    - lll
    - mnd
    - revive
    - varnamelen
    - wrapcheck
    - wsl
    - ireturn
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
