// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['pkg']['App']['Greet'](arg1);
}

export function LoginAndSync(arg1, arg2) {
  return window['go']['pkg']['App']['LoginAndSync'](arg1, arg2);
}
