// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pkg} from '../models';
import {models} from '../models';

export function DeleteOrRestore(arg1:string,arg2:Array<pkg.Request>):Promise<string>;

export function GetProjectDetail(arg1:string):Promise<string>;

export function ListProjects(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<models.ProjectSummaries>;

export function LoginAndSync(arg1:string,arg2:string):Promise<string>;
