// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pkg} from '../models';
import {models} from '../models';

export function CancelSync():Promise<void>;

export function DeleteOrRestore(arg1:string,arg2:Array<pkg.Request>):Promise<string>;

export function GetProjectDetailByID(arg1:string):Promise<Array<models.ProjectDetail>>;

export function GetSyncStatus():Promise<Record<string, any>>;

export function ListSummaries(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<models.ProjectSummaries>;

export function LoginAndSync(arg1:string,arg2:string):Promise<pkg.LoginResponse>;

export function StartSync():Promise<void>;
