// Code generated by MockGen. DO NOT EDIT.
// Source: src/request/interface.go
//
// Generated by this command:
//
//	mockgen -source=src/request/interface.go -destination=mocks/src_request/mock.go -package=mock_src_request IClient
//

// Package mock_src_request is a generated GoMock package.
package mock_src_request

import (
	context "context"
	reflect "reflect"

	logger "github.com/web4ux/src/logger"
	request "github.com/web4ux/src/request"
	gomock "go.uber.org/mock/gomock"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
	isgomock struct{}
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockIClient) Send(ctx context.Context, log logger.ILogger, in *request.SendParam) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, log, in)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockIClientMockRecorder) Send(ctx, log, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockIClient)(nil).Send), ctx, log, in)
}
