// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/fetcher/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/fetcher/interface.go -destination=mocks/internal_service_fetcher/mock.go -package=mock_internal_service_fetcher IService
//

// Package mock_internal_service_fetcher is a generated GoMock package.
package mock_internal_service_fetcher

import (
	context "context"
	reflect "reflect"

	fetcher "github.com/web4ux/internal/service/fetcher"
	htmlparser "github.com/web4ux/src/htmlparser"
	logger "github.com/web4ux/src/logger"
	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// FetchDataAndSave mocks base method.
func (m *MockIService) FetchDataAndSave(ctx context.Context, log logger.ILogger, in htmlparser.ProjectSummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataAndSave", ctx, log, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchDataAndSave indicates an expected call of FetchDataAndSave.
func (mr *MockIServiceMockRecorder) FetchDataAndSave(ctx, log, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataAndSave", reflect.TypeOf((*MockIService)(nil).FetchDataAndSave), ctx, log, in)
}

// GetProcessorRegistry mocks base method.
func (m *MockIService) GetProcessorRegistry() *fetcher.ProjectProcessorRegistry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProcessorRegistry")
	ret0, _ := ret[0].(*fetcher.ProjectProcessorRegistry)
	return ret0
}

// GetProcessorRegistry indicates an expected call of GetProcessorRegistry.
func (mr *MockIServiceMockRecorder) GetProcessorRegistry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProcessorRegistry", reflect.TypeOf((*MockIService)(nil).GetProcessorRegistry))
}

// ListAllProjects mocks base method.
func (m *MockIService) ListAllProjects(ctx context.Context, log logger.ILogger) ([]htmlparser.ProjectSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllProjects", ctx, log)
	ret0, _ := ret[0].([]htmlparser.ProjectSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllProjects indicates an expected call of ListAllProjects.
func (mr *MockIServiceMockRecorder) ListAllProjects(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllProjects", reflect.TypeOf((*MockIService)(nil).ListAllProjects), ctx, log)
}

// Login mocks base method.
func (m *MockIService) Login(ctx context.Context, log logger.ILogger, email, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, log, email, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockIServiceMockRecorder) Login(ctx, log, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIService)(nil).Login), ctx, log, email, password)
}
