// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/fetcher/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/fetcher/interface.go -destination=mocks/internal_service_fetcher/mock.go -package=mock_internal_service_fetcher ProjectTypeDetector
//

// Package mock_internal_service_fetcher is a generated GoMock package.
package mock_internal_service_fetcher

import (
	context "context"
	reflect "reflect"

	fetcher "github.com/web4ux/internal/service/fetcher"
	htmlparser "github.com/web4ux/src/htmlparser"
	logger "github.com/web4ux/src/logger"
	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// FetchDataAndSave mocks base method.
func (m *MockIService) FetchDataAndSave(ctx context.Context, log logger.ILogger, in htmlparser.ProjectSummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataAndSave", ctx, log, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchDataAndSave indicates an expected call of FetchDataAndSave.
func (mr *MockIServiceMockRecorder) FetchDataAndSave(ctx, log, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataAndSave", reflect.TypeOf((*MockIService)(nil).FetchDataAndSave), ctx, log, in)
}

// GetProcessorRegistry mocks base method.
func (m *MockIService) GetProcessorRegistry() *fetcher.ProjectProcessorRegistry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProcessorRegistry")
	ret0, _ := ret[0].(*fetcher.ProjectProcessorRegistry)
	return ret0
}

// GetProcessorRegistry indicates an expected call of GetProcessorRegistry.
func (mr *MockIServiceMockRecorder) GetProcessorRegistry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProcessorRegistry", reflect.TypeOf((*MockIService)(nil).GetProcessorRegistry))
}

// ListAllProjects mocks base method.
func (m *MockIService) ListAllProjects(ctx context.Context, log logger.ILogger) ([]htmlparser.ProjectSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllProjects", ctx, log)
	ret0, _ := ret[0].([]htmlparser.ProjectSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllProjects indicates an expected call of ListAllProjects.
func (mr *MockIServiceMockRecorder) ListAllProjects(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllProjects", reflect.TypeOf((*MockIService)(nil).ListAllProjects), ctx, log)
}

// Login mocks base method.
func (m *MockIService) Login(ctx context.Context, log logger.ILogger, email, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, log, email, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockIServiceMockRecorder) Login(ctx, log, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIService)(nil).Login), ctx, log, email, password)
}

// MockIProjectProcessor is a mock of IProjectProcessor interface.
type MockIProjectProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockIProjectProcessorMockRecorder
	isgomock struct{}
}

// MockIProjectProcessorMockRecorder is the mock recorder for MockIProjectProcessor.
type MockIProjectProcessorMockRecorder struct {
	mock *MockIProjectProcessor
}

// NewMockIProjectProcessor creates a new mock instance.
func NewMockIProjectProcessor(ctrl *gomock.Controller) *MockIProjectProcessor {
	mock := &MockIProjectProcessor{ctrl: ctrl}
	mock.recorder = &MockIProjectProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProjectProcessor) EXPECT() *MockIProjectProcessorMockRecorder {
	return m.recorder
}

// CanProcess mocks base method.
func (m *MockIProjectProcessor) CanProcess(project htmlparser.ProjectSummary) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanProcess", project)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanProcess indicates an expected call of CanProcess.
func (mr *MockIProjectProcessorMockRecorder) CanProcess(project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanProcess", reflect.TypeOf((*MockIProjectProcessor)(nil).CanProcess), project)
}

// Name mocks base method.
func (m *MockIProjectProcessor) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockIProjectProcessorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockIProjectProcessor)(nil).Name))
}

// Process mocks base method.
func (m *MockIProjectProcessor) Process(ctx context.Context, log logger.ILogger, project htmlparser.ProjectSummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, log, project)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockIProjectProcessorMockRecorder) Process(ctx, log, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockIProjectProcessor)(nil).Process), ctx, log, project)
}

// MockProgressObserver is a mock of ProgressObserver interface.
type MockProgressObserver struct {
	ctrl     *gomock.Controller
	recorder *MockProgressObserverMockRecorder
	isgomock struct{}
}

// MockProgressObserverMockRecorder is the mock recorder for MockProgressObserver.
type MockProgressObserverMockRecorder struct {
	mock *MockProgressObserver
}

// NewMockProgressObserver creates a new mock instance.
func NewMockProgressObserver(ctrl *gomock.Controller) *MockProgressObserver {
	mock := &MockProgressObserver{ctrl: ctrl}
	mock.recorder = &MockProgressObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgressObserver) EXPECT() *MockProgressObserverMockRecorder {
	return m.recorder
}

// OnProgress mocks base method.
func (m *MockProgressObserver) OnProgress(event fetcher.ProgressEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnProgress", event)
}

// OnProgress indicates an expected call of OnProgress.
func (mr *MockProgressObserverMockRecorder) OnProgress(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnProgress", reflect.TypeOf((*MockProgressObserver)(nil).OnProgress), event)
}

// MockProjectTypeDetector is a mock of ProjectTypeDetector interface.
type MockProjectTypeDetector struct {
	ctrl     *gomock.Controller
	recorder *MockProjectTypeDetectorMockRecorder
	isgomock struct{}
}

// MockProjectTypeDetectorMockRecorder is the mock recorder for MockProjectTypeDetector.
type MockProjectTypeDetectorMockRecorder struct {
	mock *MockProjectTypeDetector
}

// NewMockProjectTypeDetector creates a new mock instance.
func NewMockProjectTypeDetector(ctrl *gomock.Controller) *MockProjectTypeDetector {
	mock := &MockProjectTypeDetector{ctrl: ctrl}
	mock.recorder = &MockProjectTypeDetectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectTypeDetector) EXPECT() *MockProjectTypeDetectorMockRecorder {
	return m.recorder
}

// IsWinfittsProject mocks base method.
func (m *MockProjectTypeDetector) IsWinfittsProject(project htmlparser.ProjectSummary) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsWinfittsProject", project)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsWinfittsProject indicates an expected call of IsWinfittsProject.
func (mr *MockProjectTypeDetectorMockRecorder) IsWinfittsProject(project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsWinfittsProject", reflect.TypeOf((*MockProjectTypeDetector)(nil).IsWinfittsProject), project)
}

// MockProjectProcessor is a mock of ProjectProcessor interface.
type MockProjectProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockProjectProcessorMockRecorder
	isgomock struct{}
}

// MockProjectProcessorMockRecorder is the mock recorder for MockProjectProcessor.
type MockProjectProcessorMockRecorder struct {
	mock *MockProjectProcessor
}

// NewMockProjectProcessor creates a new mock instance.
func NewMockProjectProcessor(ctrl *gomock.Controller) *MockProjectProcessor {
	mock := &MockProjectProcessor{ctrl: ctrl}
	mock.recorder = &MockProjectProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectProcessor) EXPECT() *MockProjectProcessorMockRecorder {
	return m.recorder
}

// CanProcess mocks base method.
func (m *MockProjectProcessor) CanProcess(project htmlparser.ProjectSummary) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanProcess", project)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanProcess indicates an expected call of CanProcess.
func (mr *MockProjectProcessorMockRecorder) CanProcess(project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanProcess", reflect.TypeOf((*MockProjectProcessor)(nil).CanProcess), project)
}

// Name mocks base method.
func (m *MockProjectProcessor) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockProjectProcessorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockProjectProcessor)(nil).Name))
}

// Process mocks base method.
func (m *MockProjectProcessor) Process(ctx context.Context, log logger.ILogger, project htmlparser.ProjectSummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, log, project)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockProjectProcessorMockRecorder) Process(ctx, log, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockProjectProcessor)(nil).Process), ctx, log, project)
}
