// Code generated by MockGen. DO NOT EDIT.
// Source: repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=repository/interface.go -destination=mocks/repository/mock.go -package=mock_repository IRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	models "github.com/web4ux/models"
	sqlc "github.com/web4ux/repository/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockListProject is a mock of ListProject interface.
type MockListProject struct {
	ctrl     *gomock.Controller
	recorder *MockListProjectMockRecorder
	isgomock struct{}
}

// MockListProjectMockRecorder is the mock recorder for MockListProject.
type MockListProjectMockRecorder struct {
	mock *MockListProject
}

// NewMockListProject creates a new mock instance.
func NewMockListProject(ctrl *gomock.Controller) *MockListProject {
	mock := &MockListProject{ctrl: ctrl}
	mock.recorder = &MockListProjectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListProject) EXPECT() *MockListProjectMockRecorder {
	return m.recorder
}

// CountProjects mocks base method.
func (m *MockListProject) CountProjects(ctx context.Context, arg sqlc.CountProjectsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProjects", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProjects indicates an expected call of CountProjects.
func (mr *MockListProjectMockRecorder) CountProjects(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProjects", reflect.TypeOf((*MockListProject)(nil).CountProjects), ctx, arg)
}

// ListProjectsOrderByCreatorAsc mocks base method.
func (m *MockListProject) ListProjectsOrderByCreatorAsc(ctx context.Context, arg sqlc.ListProjectsOrderByCreatorAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByCreatorAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByCreatorAsc indicates an expected call of ListProjectsOrderByCreatorAsc.
func (mr *MockListProjectMockRecorder) ListProjectsOrderByCreatorAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByCreatorAsc", reflect.TypeOf((*MockListProject)(nil).ListProjectsOrderByCreatorAsc), ctx, arg)
}

// ListProjectsOrderByCreatorDesc mocks base method.
func (m *MockListProject) ListProjectsOrderByCreatorDesc(ctx context.Context, arg sqlc.ListProjectsOrderByCreatorDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByCreatorDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByCreatorDesc indicates an expected call of ListProjectsOrderByCreatorDesc.
func (mr *MockListProjectMockRecorder) ListProjectsOrderByCreatorDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByCreatorDesc", reflect.TypeOf((*MockListProject)(nil).ListProjectsOrderByCreatorDesc), ctx, arg)
}

// ListProjectsOrderByNameAsc mocks base method.
func (m *MockListProject) ListProjectsOrderByNameAsc(ctx context.Context, arg sqlc.ListProjectsOrderByNameAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByNameAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByNameAsc indicates an expected call of ListProjectsOrderByNameAsc.
func (mr *MockListProjectMockRecorder) ListProjectsOrderByNameAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByNameAsc", reflect.TypeOf((*MockListProject)(nil).ListProjectsOrderByNameAsc), ctx, arg)
}

// ListProjectsOrderByNameDesc mocks base method.
func (m *MockListProject) ListProjectsOrderByNameDesc(ctx context.Context, arg sqlc.ListProjectsOrderByNameDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByNameDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByNameDesc indicates an expected call of ListProjectsOrderByNameDesc.
func (mr *MockListProjectMockRecorder) ListProjectsOrderByNameDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByNameDesc", reflect.TypeOf((*MockListProject)(nil).ListProjectsOrderByNameDesc), ctx, arg)
}

// ListProjectsOrderByUpdatedAtAsc mocks base method.
func (m *MockListProject) ListProjectsOrderByUpdatedAtAsc(ctx context.Context, arg sqlc.ListProjectsOrderByUpdatedAtAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByUpdatedAtAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByUpdatedAtAsc indicates an expected call of ListProjectsOrderByUpdatedAtAsc.
func (mr *MockListProjectMockRecorder) ListProjectsOrderByUpdatedAtAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByUpdatedAtAsc", reflect.TypeOf((*MockListProject)(nil).ListProjectsOrderByUpdatedAtAsc), ctx, arg)
}

// ListProjectsOrderByUpdatedAtDesc mocks base method.
func (m *MockListProject) ListProjectsOrderByUpdatedAtDesc(ctx context.Context, arg sqlc.ListProjectsOrderByUpdatedAtDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByUpdatedAtDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByUpdatedAtDesc indicates an expected call of ListProjectsOrderByUpdatedAtDesc.
func (mr *MockListProjectMockRecorder) ListProjectsOrderByUpdatedAtDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByUpdatedAtDesc", reflect.TypeOf((*MockListProject)(nil).ListProjectsOrderByUpdatedAtDesc), ctx, arg)
}

// MockCommand is a mock of Command interface.
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
	isgomock struct{}
}

// MockCommandMockRecorder is the mock recorder for MockCommand.
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance.
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// DeleteWinfittsInformation mocks base method.
func (m *MockCommand) DeleteWinfittsInformation(ctx context.Context, arg sqlc.DeleteWinfittsInformationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWinfittsInformation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWinfittsInformation indicates an expected call of DeleteWinfittsInformation.
func (mr *MockCommandMockRecorder) DeleteWinfittsInformation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWinfittsInformation", reflect.TypeOf((*MockCommand)(nil).DeleteWinfittsInformation), ctx, arg)
}

// UpsertDevices mocks base method.
func (m *MockCommand) UpsertDevices(ctx context.Context, arg sqlc.UpsertDevicesParams) (sqlc.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDevices", ctx, arg)
	ret0, _ := ret[0].(sqlc.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertDevices indicates an expected call of UpsertDevices.
func (mr *MockCommandMockRecorder) UpsertDevices(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDevices", reflect.TypeOf((*MockCommand)(nil).UpsertDevices), ctx, arg)
}

// UpsertParticipants mocks base method.
func (m *MockCommand) UpsertParticipants(ctx context.Context, arg sqlc.UpsertParticipantsParams) (sqlc.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertParticipants", ctx, arg)
	ret0, _ := ret[0].(sqlc.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertParticipants indicates an expected call of UpsertParticipants.
func (mr *MockCommandMockRecorder) UpsertParticipants(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertParticipants", reflect.TypeOf((*MockCommand)(nil).UpsertParticipants), ctx, arg)
}

// UpsertProject mocks base method.
func (m *MockCommand) UpsertProject(ctx context.Context, arg sqlc.UpsertProjectParams) (sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertProject", ctx, arg)
	ret0, _ := ret[0].(sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertProject indicates an expected call of UpsertProject.
func (mr *MockCommandMockRecorder) UpsertProject(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertProject", reflect.TypeOf((*MockCommand)(nil).UpsertProject), ctx, arg)
}

// UpsertWinfitts mocks base method.
func (m *MockCommand) UpsertWinfitts(ctx context.Context, arg sqlc.UpsertWinfittsParams) (sqlc.Winfitt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWinfitts", ctx, arg)
	ret0, _ := ret[0].(sqlc.Winfitt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertWinfitts indicates an expected call of UpsertWinfitts.
func (mr *MockCommandMockRecorder) UpsertWinfitts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWinfitts", reflect.TypeOf((*MockCommand)(nil).UpsertWinfitts), ctx, arg)
}

// UpsertWinfittsDetail mocks base method.
func (m *MockCommand) UpsertWinfittsDetail(ctx context.Context, arg sqlc.UpsertWinfittsDetailParams) (sqlc.WinfittsDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWinfittsDetail", ctx, arg)
	ret0, _ := ret[0].(sqlc.WinfittsDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertWinfittsDetail indicates an expected call of UpsertWinfittsDetail.
func (mr *MockCommandMockRecorder) UpsertWinfittsDetail(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWinfittsDetail", reflect.TypeOf((*MockCommand)(nil).UpsertWinfittsDetail), ctx, arg)
}

// UpsertWinfittsInformation mocks base method.
func (m *MockCommand) UpsertWinfittsInformation(ctx context.Context, arg sqlc.UpsertWinfittsInformationParams) (sqlc.WinfittsInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWinfittsInformation", ctx, arg)
	ret0, _ := ret[0].(sqlc.WinfittsInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertWinfittsInformation indicates an expected call of UpsertWinfittsInformation.
func (mr *MockCommandMockRecorder) UpsertWinfittsInformation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWinfittsInformation", reflect.TypeOf((*MockCommand)(nil).UpsertWinfittsInformation), ctx, arg)
}

// MockQueries is a mock of Queries interface.
type MockQueries struct {
	ctrl     *gomock.Controller
	recorder *MockQueriesMockRecorder
	isgomock struct{}
}

// MockQueriesMockRecorder is the mock recorder for MockQueries.
type MockQueriesMockRecorder struct {
	mock *MockQueries
}

// NewMockQueries creates a new mock instance.
func NewMockQueries(ctrl *gomock.Controller) *MockQueries {
	mock := &MockQueries{ctrl: ctrl}
	mock.recorder = &MockQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueries) EXPECT() *MockQueriesMockRecorder {
	return m.recorder
}

// CountProjects mocks base method.
func (m *MockQueries) CountProjects(ctx context.Context, arg sqlc.CountProjectsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProjects", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProjects indicates an expected call of CountProjects.
func (mr *MockQueriesMockRecorder) CountProjects(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProjects", reflect.TypeOf((*MockQueries)(nil).CountProjects), ctx, arg)
}

// GetProject mocks base method.
func (m *MockQueries) GetProject(ctx context.Context, id string) (sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, id)
	ret0, _ := ret[0].(sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockQueriesMockRecorder) GetProject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockQueries)(nil).GetProject), ctx, id)
}

// GetProjectDetailByID mocks base method.
func (m *MockQueries) GetProjectDetailByID(ctx context.Context, projectID string) ([]sqlc.GetProjectDetailByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectDetailByID", ctx, projectID)
	ret0, _ := ret[0].([]sqlc.GetProjectDetailByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectDetailByID indicates an expected call of GetProjectDetailByID.
func (mr *MockQueriesMockRecorder) GetProjectDetailByID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectDetailByID", reflect.TypeOf((*MockQueries)(nil).GetProjectDetailByID), ctx, projectID)
}

// ListProjectsOrderByCreatorAsc mocks base method.
func (m *MockQueries) ListProjectsOrderByCreatorAsc(ctx context.Context, arg sqlc.ListProjectsOrderByCreatorAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByCreatorAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByCreatorAsc indicates an expected call of ListProjectsOrderByCreatorAsc.
func (mr *MockQueriesMockRecorder) ListProjectsOrderByCreatorAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByCreatorAsc", reflect.TypeOf((*MockQueries)(nil).ListProjectsOrderByCreatorAsc), ctx, arg)
}

// ListProjectsOrderByCreatorDesc mocks base method.
func (m *MockQueries) ListProjectsOrderByCreatorDesc(ctx context.Context, arg sqlc.ListProjectsOrderByCreatorDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByCreatorDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByCreatorDesc indicates an expected call of ListProjectsOrderByCreatorDesc.
func (mr *MockQueriesMockRecorder) ListProjectsOrderByCreatorDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByCreatorDesc", reflect.TypeOf((*MockQueries)(nil).ListProjectsOrderByCreatorDesc), ctx, arg)
}

// ListProjectsOrderByNameAsc mocks base method.
func (m *MockQueries) ListProjectsOrderByNameAsc(ctx context.Context, arg sqlc.ListProjectsOrderByNameAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByNameAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByNameAsc indicates an expected call of ListProjectsOrderByNameAsc.
func (mr *MockQueriesMockRecorder) ListProjectsOrderByNameAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByNameAsc", reflect.TypeOf((*MockQueries)(nil).ListProjectsOrderByNameAsc), ctx, arg)
}

// ListProjectsOrderByNameDesc mocks base method.
func (m *MockQueries) ListProjectsOrderByNameDesc(ctx context.Context, arg sqlc.ListProjectsOrderByNameDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByNameDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByNameDesc indicates an expected call of ListProjectsOrderByNameDesc.
func (mr *MockQueriesMockRecorder) ListProjectsOrderByNameDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByNameDesc", reflect.TypeOf((*MockQueries)(nil).ListProjectsOrderByNameDesc), ctx, arg)
}

// ListProjectsOrderByUpdatedAtAsc mocks base method.
func (m *MockQueries) ListProjectsOrderByUpdatedAtAsc(ctx context.Context, arg sqlc.ListProjectsOrderByUpdatedAtAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByUpdatedAtAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByUpdatedAtAsc indicates an expected call of ListProjectsOrderByUpdatedAtAsc.
func (mr *MockQueriesMockRecorder) ListProjectsOrderByUpdatedAtAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByUpdatedAtAsc", reflect.TypeOf((*MockQueries)(nil).ListProjectsOrderByUpdatedAtAsc), ctx, arg)
}

// ListProjectsOrderByUpdatedAtDesc mocks base method.
func (m *MockQueries) ListProjectsOrderByUpdatedAtDesc(ctx context.Context, arg sqlc.ListProjectsOrderByUpdatedAtDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByUpdatedAtDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByUpdatedAtDesc indicates an expected call of ListProjectsOrderByUpdatedAtDesc.
func (mr *MockQueriesMockRecorder) ListProjectsOrderByUpdatedAtDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByUpdatedAtDesc", reflect.TypeOf((*MockQueries)(nil).ListProjectsOrderByUpdatedAtDesc), ctx, arg)
}

// MockIDatabase is a mock of IDatabase interface.
type MockIDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockIDatabaseMockRecorder
	isgomock struct{}
}

// MockIDatabaseMockRecorder is the mock recorder for MockIDatabase.
type MockIDatabaseMockRecorder struct {
	mock *MockIDatabase
}

// NewMockIDatabase creates a new mock instance.
func NewMockIDatabase(ctrl *gomock.Controller) *MockIDatabase {
	mock := &MockIDatabase{ctrl: ctrl}
	mock.recorder = &MockIDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDatabase) EXPECT() *MockIDatabaseMockRecorder {
	return m.recorder
}

// CountProjects mocks base method.
func (m *MockIDatabase) CountProjects(ctx context.Context, arg sqlc.CountProjectsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProjects", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProjects indicates an expected call of CountProjects.
func (mr *MockIDatabaseMockRecorder) CountProjects(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProjects", reflect.TypeOf((*MockIDatabase)(nil).CountProjects), ctx, arg)
}

// DeleteWinfittsInformation mocks base method.
func (m *MockIDatabase) DeleteWinfittsInformation(ctx context.Context, arg sqlc.DeleteWinfittsInformationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWinfittsInformation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWinfittsInformation indicates an expected call of DeleteWinfittsInformation.
func (mr *MockIDatabaseMockRecorder) DeleteWinfittsInformation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWinfittsInformation", reflect.TypeOf((*MockIDatabase)(nil).DeleteWinfittsInformation), ctx, arg)
}

// GetProject mocks base method.
func (m *MockIDatabase) GetProject(ctx context.Context, id string) (sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, id)
	ret0, _ := ret[0].(sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockIDatabaseMockRecorder) GetProject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockIDatabase)(nil).GetProject), ctx, id)
}

// GetProjectDetailByID mocks base method.
func (m *MockIDatabase) GetProjectDetailByID(ctx context.Context, projectID string) ([]sqlc.GetProjectDetailByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectDetailByID", ctx, projectID)
	ret0, _ := ret[0].([]sqlc.GetProjectDetailByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectDetailByID indicates an expected call of GetProjectDetailByID.
func (mr *MockIDatabaseMockRecorder) GetProjectDetailByID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectDetailByID", reflect.TypeOf((*MockIDatabase)(nil).GetProjectDetailByID), ctx, projectID)
}

// ListProjectsOrderByCreatorAsc mocks base method.
func (m *MockIDatabase) ListProjectsOrderByCreatorAsc(ctx context.Context, arg sqlc.ListProjectsOrderByCreatorAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByCreatorAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByCreatorAsc indicates an expected call of ListProjectsOrderByCreatorAsc.
func (mr *MockIDatabaseMockRecorder) ListProjectsOrderByCreatorAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByCreatorAsc", reflect.TypeOf((*MockIDatabase)(nil).ListProjectsOrderByCreatorAsc), ctx, arg)
}

// ListProjectsOrderByCreatorDesc mocks base method.
func (m *MockIDatabase) ListProjectsOrderByCreatorDesc(ctx context.Context, arg sqlc.ListProjectsOrderByCreatorDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByCreatorDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByCreatorDesc indicates an expected call of ListProjectsOrderByCreatorDesc.
func (mr *MockIDatabaseMockRecorder) ListProjectsOrderByCreatorDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByCreatorDesc", reflect.TypeOf((*MockIDatabase)(nil).ListProjectsOrderByCreatorDesc), ctx, arg)
}

// ListProjectsOrderByNameAsc mocks base method.
func (m *MockIDatabase) ListProjectsOrderByNameAsc(ctx context.Context, arg sqlc.ListProjectsOrderByNameAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByNameAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByNameAsc indicates an expected call of ListProjectsOrderByNameAsc.
func (mr *MockIDatabaseMockRecorder) ListProjectsOrderByNameAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByNameAsc", reflect.TypeOf((*MockIDatabase)(nil).ListProjectsOrderByNameAsc), ctx, arg)
}

// ListProjectsOrderByNameDesc mocks base method.
func (m *MockIDatabase) ListProjectsOrderByNameDesc(ctx context.Context, arg sqlc.ListProjectsOrderByNameDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByNameDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByNameDesc indicates an expected call of ListProjectsOrderByNameDesc.
func (mr *MockIDatabaseMockRecorder) ListProjectsOrderByNameDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByNameDesc", reflect.TypeOf((*MockIDatabase)(nil).ListProjectsOrderByNameDesc), ctx, arg)
}

// ListProjectsOrderByUpdatedAtAsc mocks base method.
func (m *MockIDatabase) ListProjectsOrderByUpdatedAtAsc(ctx context.Context, arg sqlc.ListProjectsOrderByUpdatedAtAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByUpdatedAtAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByUpdatedAtAsc indicates an expected call of ListProjectsOrderByUpdatedAtAsc.
func (mr *MockIDatabaseMockRecorder) ListProjectsOrderByUpdatedAtAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByUpdatedAtAsc", reflect.TypeOf((*MockIDatabase)(nil).ListProjectsOrderByUpdatedAtAsc), ctx, arg)
}

// ListProjectsOrderByUpdatedAtDesc mocks base method.
func (m *MockIDatabase) ListProjectsOrderByUpdatedAtDesc(ctx context.Context, arg sqlc.ListProjectsOrderByUpdatedAtDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsOrderByUpdatedAtDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsOrderByUpdatedAtDesc indicates an expected call of ListProjectsOrderByUpdatedAtDesc.
func (mr *MockIDatabaseMockRecorder) ListProjectsOrderByUpdatedAtDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsOrderByUpdatedAtDesc", reflect.TypeOf((*MockIDatabase)(nil).ListProjectsOrderByUpdatedAtDesc), ctx, arg)
}

// UpsertDevices mocks base method.
func (m *MockIDatabase) UpsertDevices(ctx context.Context, arg sqlc.UpsertDevicesParams) (sqlc.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDevices", ctx, arg)
	ret0, _ := ret[0].(sqlc.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertDevices indicates an expected call of UpsertDevices.
func (mr *MockIDatabaseMockRecorder) UpsertDevices(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDevices", reflect.TypeOf((*MockIDatabase)(nil).UpsertDevices), ctx, arg)
}

// UpsertParticipants mocks base method.
func (m *MockIDatabase) UpsertParticipants(ctx context.Context, arg sqlc.UpsertParticipantsParams) (sqlc.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertParticipants", ctx, arg)
	ret0, _ := ret[0].(sqlc.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertParticipants indicates an expected call of UpsertParticipants.
func (mr *MockIDatabaseMockRecorder) UpsertParticipants(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertParticipants", reflect.TypeOf((*MockIDatabase)(nil).UpsertParticipants), ctx, arg)
}

// UpsertProject mocks base method.
func (m *MockIDatabase) UpsertProject(ctx context.Context, arg sqlc.UpsertProjectParams) (sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertProject", ctx, arg)
	ret0, _ := ret[0].(sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertProject indicates an expected call of UpsertProject.
func (mr *MockIDatabaseMockRecorder) UpsertProject(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertProject", reflect.TypeOf((*MockIDatabase)(nil).UpsertProject), ctx, arg)
}

// UpsertWinfitts mocks base method.
func (m *MockIDatabase) UpsertWinfitts(ctx context.Context, arg sqlc.UpsertWinfittsParams) (sqlc.Winfitt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWinfitts", ctx, arg)
	ret0, _ := ret[0].(sqlc.Winfitt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertWinfitts indicates an expected call of UpsertWinfitts.
func (mr *MockIDatabaseMockRecorder) UpsertWinfitts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWinfitts", reflect.TypeOf((*MockIDatabase)(nil).UpsertWinfitts), ctx, arg)
}

// UpsertWinfittsDetail mocks base method.
func (m *MockIDatabase) UpsertWinfittsDetail(ctx context.Context, arg sqlc.UpsertWinfittsDetailParams) (sqlc.WinfittsDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWinfittsDetail", ctx, arg)
	ret0, _ := ret[0].(sqlc.WinfittsDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertWinfittsDetail indicates an expected call of UpsertWinfittsDetail.
func (mr *MockIDatabaseMockRecorder) UpsertWinfittsDetail(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWinfittsDetail", reflect.TypeOf((*MockIDatabase)(nil).UpsertWinfittsDetail), ctx, arg)
}

// UpsertWinfittsInformation mocks base method.
func (m *MockIDatabase) UpsertWinfittsInformation(ctx context.Context, arg sqlc.UpsertWinfittsInformationParams) (sqlc.WinfittsInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWinfittsInformation", ctx, arg)
	ret0, _ := ret[0].(sqlc.WinfittsInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertWinfittsInformation indicates an expected call of UpsertWinfittsInformation.
func (mr *MockIDatabaseMockRecorder) UpsertWinfittsInformation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWinfittsInformation", reflect.TypeOf((*MockIDatabase)(nil).UpsertWinfittsInformation), ctx, arg)
}

// WithTx mocks base method.
func (m *MockIDatabase) WithTx(tx *sql.Tx) *sqlc.Queries {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(*sqlc.Queries)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockIDatabaseMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockIDatabase)(nil).WithTx), tx)
}

// MockCommandRepository is a mock of CommandRepository interface.
type MockCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockCommandRepositoryMockRecorder is the mock recorder for MockCommandRepository.
type MockCommandRepositoryMockRecorder struct {
	mock *MockCommandRepository
}

// NewMockCommandRepository creates a new mock instance.
func NewMockCommandRepository(ctrl *gomock.Controller) *MockCommandRepository {
	mock := &MockCommandRepository{ctrl: ctrl}
	mock.recorder = &MockCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandRepository) EXPECT() *MockCommandRepositoryMockRecorder {
	return m.recorder
}

// DeleteOrRestoreWinfittsInformation mocks base method.
func (m *MockCommandRepository) DeleteOrRestoreWinfittsInformation(ctx context.Context, arg sqlc.DeleteWinfittsInformationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrRestoreWinfittsInformation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrRestoreWinfittsInformation indicates an expected call of DeleteOrRestoreWinfittsInformation.
func (mr *MockCommandRepositoryMockRecorder) DeleteOrRestoreWinfittsInformation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrRestoreWinfittsInformation", reflect.TypeOf((*MockCommandRepository)(nil).DeleteOrRestoreWinfittsInformation), ctx, arg)
}

// UpsertExtractWinfittsDetails mocks base method.
func (m *MockCommandRepository) UpsertExtractWinfittsDetails(ctx context.Context, in models.ProjectSummary, rows []models.WinfittsRawData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertExtractWinfittsDetails", ctx, in, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertExtractWinfittsDetails indicates an expected call of UpsertExtractWinfittsDetails.
func (mr *MockCommandRepositoryMockRecorder) UpsertExtractWinfittsDetails(ctx, in, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertExtractWinfittsDetails", reflect.TypeOf((*MockCommandRepository)(nil).UpsertExtractWinfittsDetails), ctx, in, rows)
}

// MockQueryRepository is a mock of QueryRepository interface.
type MockQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockQueryRepositoryMockRecorder is the mock recorder for MockQueryRepository.
type MockQueryRepositoryMockRecorder struct {
	mock *MockQueryRepository
}

// NewMockQueryRepository creates a new mock instance.
func NewMockQueryRepository(ctrl *gomock.Controller) *MockQueryRepository {
	mock := &MockQueryRepository{ctrl: ctrl}
	mock.recorder = &MockQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryRepository) EXPECT() *MockQueryRepositoryMockRecorder {
	return m.recorder
}

// GetProject mocks base method.
func (m *MockQueryRepository) GetProject(ctx context.Context, id string) (models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, id)
	ret0, _ := ret[0].(models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockQueryRepositoryMockRecorder) GetProject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockQueryRepository)(nil).GetProject), ctx, id)
}

// GetProjectDetailByID mocks base method.
func (m *MockQueryRepository) GetProjectDetailByID(ctx context.Context, projectID string) ([]models.ProjectDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectDetailByID", ctx, projectID)
	ret0, _ := ret[0].([]models.ProjectDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectDetailByID indicates an expected call of GetProjectDetailByID.
func (mr *MockQueryRepositoryMockRecorder) GetProjectDetailByID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectDetailByID", reflect.TypeOf((*MockQueryRepository)(nil).GetProjectDetailByID), ctx, projectID)
}

// ListProjects mocks base method.
func (m *MockQueryRepository) ListProjects(ctx context.Context, name, creator, orderBy, direction string, offset, limit int64) (models.ProjectSummaries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx, name, creator, orderBy, direction, offset, limit)
	ret0, _ := ret[0].(models.ProjectSummaries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockQueryRepositoryMockRecorder) ListProjects(ctx, name, creator, orderBy, direction, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockQueryRepository)(nil).ListProjects), ctx, name, creator, orderBy, direction, offset, limit)
}

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
	isgomock struct{}
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// DeleteOrRestoreWinfittsInformation mocks base method.
func (m *MockIRepository) DeleteOrRestoreWinfittsInformation(ctx context.Context, arg sqlc.DeleteWinfittsInformationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrRestoreWinfittsInformation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrRestoreWinfittsInformation indicates an expected call of DeleteOrRestoreWinfittsInformation.
func (mr *MockIRepositoryMockRecorder) DeleteOrRestoreWinfittsInformation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrRestoreWinfittsInformation", reflect.TypeOf((*MockIRepository)(nil).DeleteOrRestoreWinfittsInformation), ctx, arg)
}

// GetProject mocks base method.
func (m *MockIRepository) GetProject(ctx context.Context, id string) (models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, id)
	ret0, _ := ret[0].(models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockIRepositoryMockRecorder) GetProject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockIRepository)(nil).GetProject), ctx, id)
}

// GetProjectDetailByID mocks base method.
func (m *MockIRepository) GetProjectDetailByID(ctx context.Context, projectID string) ([]models.ProjectDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectDetailByID", ctx, projectID)
	ret0, _ := ret[0].([]models.ProjectDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectDetailByID indicates an expected call of GetProjectDetailByID.
func (mr *MockIRepositoryMockRecorder) GetProjectDetailByID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectDetailByID", reflect.TypeOf((*MockIRepository)(nil).GetProjectDetailByID), ctx, projectID)
}

// ListProjects mocks base method.
func (m *MockIRepository) ListProjects(ctx context.Context, name, creator, orderBy, direction string, offset, limit int64) (models.ProjectSummaries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx, name, creator, orderBy, direction, offset, limit)
	ret0, _ := ret[0].(models.ProjectSummaries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockIRepositoryMockRecorder) ListProjects(ctx, name, creator, orderBy, direction, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockIRepository)(nil).ListProjects), ctx, name, creator, orderBy, direction, offset, limit)
}

// UpsertExtractWinfittsDetails mocks base method.
func (m *MockIRepository) UpsertExtractWinfittsDetails(ctx context.Context, in models.ProjectSummary, rows []models.WinfittsRawData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertExtractWinfittsDetails", ctx, in, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertExtractWinfittsDetails indicates an expected call of UpsertExtractWinfittsDetails.
func (mr *MockIRepositoryMockRecorder) UpsertExtractWinfittsDetails(ctx, in, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertExtractWinfittsDetails", reflect.TypeOf((*MockIRepository)(nil).UpsertExtractWinfittsDetails), ctx, in, rows)
}
