// Code generated by MockGen. DO NOT EDIT.
// Source: repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=repository/interface.go -destination=mocks/repository/mock.go -package=mock_repository IRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	models "github.com/web4ux/models"
	sqlc "github.com/web4ux/repository/sqlc"
	logger "github.com/web4ux/src/logger"
	gomock "go.uber.org/mock/gomock"
)

// MockListProject is a mock of ListProject interface.
type MockListProject struct {
	ctrl     *gomock.Controller
	recorder *MockListProjectMockRecorder
	isgomock struct{}
}

// MockListProjectMockRecorder is the mock recorder for MockListProject.
type MockListProjectMockRecorder struct {
	mock *MockListProject
}

// NewMockListProject creates a new mock instance.
func NewMockListProject(ctrl *gomock.Controller) *MockListProject {
	mock := &MockListProject{ctrl: ctrl}
	mock.recorder = &MockListProjectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListProject) EXPECT() *MockListProjectMockRecorder {
	return m.recorder
}

// CountProjects mocks base method.
func (m *MockListProject) CountProjects(ctx context.Context, arg sqlc.CountProjectsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProjects", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProjects indicates an expected call of CountProjects.
func (mr *MockListProjectMockRecorder) CountProjects(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProjects", reflect.TypeOf((*MockListProject)(nil).CountProjects), ctx, arg)
}

// ListProjectsByCreatorAsc mocks base method.
func (m *MockListProject) ListProjectsByCreatorAsc(ctx context.Context, arg sqlc.ListProjectsByCreatorAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByCreatorAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByCreatorAsc indicates an expected call of ListProjectsByCreatorAsc.
func (mr *MockListProjectMockRecorder) ListProjectsByCreatorAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByCreatorAsc", reflect.TypeOf((*MockListProject)(nil).ListProjectsByCreatorAsc), ctx, arg)
}

// ListProjectsByCreatorDesc mocks base method.
func (m *MockListProject) ListProjectsByCreatorDesc(ctx context.Context, arg sqlc.ListProjectsByCreatorDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByCreatorDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByCreatorDesc indicates an expected call of ListProjectsByCreatorDesc.
func (mr *MockListProjectMockRecorder) ListProjectsByCreatorDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByCreatorDesc", reflect.TypeOf((*MockListProject)(nil).ListProjectsByCreatorDesc), ctx, arg)
}

// ListProjectsByNameAsc mocks base method.
func (m *MockListProject) ListProjectsByNameAsc(ctx context.Context, arg sqlc.ListProjectsByNameAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByNameAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByNameAsc indicates an expected call of ListProjectsByNameAsc.
func (mr *MockListProjectMockRecorder) ListProjectsByNameAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByNameAsc", reflect.TypeOf((*MockListProject)(nil).ListProjectsByNameAsc), ctx, arg)
}

// ListProjectsByNameDesc mocks base method.
func (m *MockListProject) ListProjectsByNameDesc(ctx context.Context, arg sqlc.ListProjectsByNameDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByNameDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByNameDesc indicates an expected call of ListProjectsByNameDesc.
func (mr *MockListProjectMockRecorder) ListProjectsByNameDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByNameDesc", reflect.TypeOf((*MockListProject)(nil).ListProjectsByNameDesc), ctx, arg)
}

// ListProjectsByTimeAsc mocks base method.
func (m *MockListProject) ListProjectsByTimeAsc(ctx context.Context, arg sqlc.ListProjectsByTimeAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByTimeAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByTimeAsc indicates an expected call of ListProjectsByTimeAsc.
func (mr *MockListProjectMockRecorder) ListProjectsByTimeAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByTimeAsc", reflect.TypeOf((*MockListProject)(nil).ListProjectsByTimeAsc), ctx, arg)
}

// ListProjectsByTimeDesc mocks base method.
func (m *MockListProject) ListProjectsByTimeDesc(ctx context.Context, arg sqlc.ListProjectsByTimeDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByTimeDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByTimeDesc indicates an expected call of ListProjectsByTimeDesc.
func (mr *MockListProjectMockRecorder) ListProjectsByTimeDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByTimeDesc", reflect.TypeOf((*MockListProject)(nil).ListProjectsByTimeDesc), ctx, arg)
}

// MockCommand is a mock of Command interface.
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
	isgomock struct{}
}

// MockCommandMockRecorder is the mock recorder for MockCommand.
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance.
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// SoftDeleteWinfittsInformation mocks base method.
func (m *MockCommand) SoftDeleteWinfittsInformation(ctx context.Context, arg sqlc.SoftDeleteWinfittsInformationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteWinfittsInformation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteWinfittsInformation indicates an expected call of SoftDeleteWinfittsInformation.
func (mr *MockCommandMockRecorder) SoftDeleteWinfittsInformation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteWinfittsInformation", reflect.TypeOf((*MockCommand)(nil).SoftDeleteWinfittsInformation), ctx, arg)
}

// UpsertDevices mocks base method.
func (m *MockCommand) UpsertDevices(ctx context.Context, arg sqlc.UpsertDevicesParams) (sqlc.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDevices", ctx, arg)
	ret0, _ := ret[0].(sqlc.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertDevices indicates an expected call of UpsertDevices.
func (mr *MockCommandMockRecorder) UpsertDevices(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDevices", reflect.TypeOf((*MockCommand)(nil).UpsertDevices), ctx, arg)
}

// UpsertParticipants mocks base method.
func (m *MockCommand) UpsertParticipants(ctx context.Context, arg sqlc.UpsertParticipantsParams) (sqlc.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertParticipants", ctx, arg)
	ret0, _ := ret[0].(sqlc.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertParticipants indicates an expected call of UpsertParticipants.
func (mr *MockCommandMockRecorder) UpsertParticipants(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertParticipants", reflect.TypeOf((*MockCommand)(nil).UpsertParticipants), ctx, arg)
}

// UpsertProject mocks base method.
func (m *MockCommand) UpsertProject(ctx context.Context, arg sqlc.UpsertProjectParams) (sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertProject", ctx, arg)
	ret0, _ := ret[0].(sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertProject indicates an expected call of UpsertProject.
func (mr *MockCommandMockRecorder) UpsertProject(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertProject", reflect.TypeOf((*MockCommand)(nil).UpsertProject), ctx, arg)
}

// UpsertWinfitts mocks base method.
func (m *MockCommand) UpsertWinfitts(ctx context.Context, arg sqlc.UpsertWinfittsParams) (sqlc.Winfitt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWinfitts", ctx, arg)
	ret0, _ := ret[0].(sqlc.Winfitt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertWinfitts indicates an expected call of UpsertWinfitts.
func (mr *MockCommandMockRecorder) UpsertWinfitts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWinfitts", reflect.TypeOf((*MockCommand)(nil).UpsertWinfitts), ctx, arg)
}

// UpsertWinfittsDetail mocks base method.
func (m *MockCommand) UpsertWinfittsDetail(ctx context.Context, arg sqlc.UpsertWinfittsDetailParams) (sqlc.WinfittsDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWinfittsDetail", ctx, arg)
	ret0, _ := ret[0].(sqlc.WinfittsDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertWinfittsDetail indicates an expected call of UpsertWinfittsDetail.
func (mr *MockCommandMockRecorder) UpsertWinfittsDetail(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWinfittsDetail", reflect.TypeOf((*MockCommand)(nil).UpsertWinfittsDetail), ctx, arg)
}

// UpsertWinfittsInformation mocks base method.
func (m *MockCommand) UpsertWinfittsInformation(ctx context.Context, arg sqlc.UpsertWinfittsInformationParams) (sqlc.WinfittsInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWinfittsInformation", ctx, arg)
	ret0, _ := ret[0].(sqlc.WinfittsInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertWinfittsInformation indicates an expected call of UpsertWinfittsInformation.
func (mr *MockCommandMockRecorder) UpsertWinfittsInformation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWinfittsInformation", reflect.TypeOf((*MockCommand)(nil).UpsertWinfittsInformation), ctx, arg)
}

// MockQueries is a mock of Queries interface.
type MockQueries struct {
	ctrl     *gomock.Controller
	recorder *MockQueriesMockRecorder
	isgomock struct{}
}

// MockQueriesMockRecorder is the mock recorder for MockQueries.
type MockQueriesMockRecorder struct {
	mock *MockQueries
}

// NewMockQueries creates a new mock instance.
func NewMockQueries(ctrl *gomock.Controller) *MockQueries {
	mock := &MockQueries{ctrl: ctrl}
	mock.recorder = &MockQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueries) EXPECT() *MockQueriesMockRecorder {
	return m.recorder
}

// CountProjects mocks base method.
func (m *MockQueries) CountProjects(ctx context.Context, arg sqlc.CountProjectsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProjects", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProjects indicates an expected call of CountProjects.
func (mr *MockQueriesMockRecorder) CountProjects(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProjects", reflect.TypeOf((*MockQueries)(nil).CountProjects), ctx, arg)
}

// FindProject mocks base method.
func (m *MockQueries) FindProject(ctx context.Context, id string) (sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProject", ctx, id)
	ret0, _ := ret[0].(sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProject indicates an expected call of FindProject.
func (mr *MockQueriesMockRecorder) FindProject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProject", reflect.TypeOf((*MockQueries)(nil).FindProject), ctx, id)
}

// FindProjectDetails mocks base method.
func (m *MockQueries) FindProjectDetails(ctx context.Context, projectID string) ([]sqlc.FindProjectDetailsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProjectDetails", ctx, projectID)
	ret0, _ := ret[0].([]sqlc.FindProjectDetailsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProjectDetails indicates an expected call of FindProjectDetails.
func (mr *MockQueriesMockRecorder) FindProjectDetails(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProjectDetails", reflect.TypeOf((*MockQueries)(nil).FindProjectDetails), ctx, projectID)
}

// ListProjectsByCreatorAsc mocks base method.
func (m *MockQueries) ListProjectsByCreatorAsc(ctx context.Context, arg sqlc.ListProjectsByCreatorAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByCreatorAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByCreatorAsc indicates an expected call of ListProjectsByCreatorAsc.
func (mr *MockQueriesMockRecorder) ListProjectsByCreatorAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByCreatorAsc", reflect.TypeOf((*MockQueries)(nil).ListProjectsByCreatorAsc), ctx, arg)
}

// ListProjectsByCreatorDesc mocks base method.
func (m *MockQueries) ListProjectsByCreatorDesc(ctx context.Context, arg sqlc.ListProjectsByCreatorDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByCreatorDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByCreatorDesc indicates an expected call of ListProjectsByCreatorDesc.
func (mr *MockQueriesMockRecorder) ListProjectsByCreatorDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByCreatorDesc", reflect.TypeOf((*MockQueries)(nil).ListProjectsByCreatorDesc), ctx, arg)
}

// ListProjectsByNameAsc mocks base method.
func (m *MockQueries) ListProjectsByNameAsc(ctx context.Context, arg sqlc.ListProjectsByNameAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByNameAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByNameAsc indicates an expected call of ListProjectsByNameAsc.
func (mr *MockQueriesMockRecorder) ListProjectsByNameAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByNameAsc", reflect.TypeOf((*MockQueries)(nil).ListProjectsByNameAsc), ctx, arg)
}

// ListProjectsByNameDesc mocks base method.
func (m *MockQueries) ListProjectsByNameDesc(ctx context.Context, arg sqlc.ListProjectsByNameDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByNameDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByNameDesc indicates an expected call of ListProjectsByNameDesc.
func (mr *MockQueriesMockRecorder) ListProjectsByNameDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByNameDesc", reflect.TypeOf((*MockQueries)(nil).ListProjectsByNameDesc), ctx, arg)
}

// ListProjectsByTimeAsc mocks base method.
func (m *MockQueries) ListProjectsByTimeAsc(ctx context.Context, arg sqlc.ListProjectsByTimeAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByTimeAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByTimeAsc indicates an expected call of ListProjectsByTimeAsc.
func (mr *MockQueriesMockRecorder) ListProjectsByTimeAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByTimeAsc", reflect.TypeOf((*MockQueries)(nil).ListProjectsByTimeAsc), ctx, arg)
}

// ListProjectsByTimeDesc mocks base method.
func (m *MockQueries) ListProjectsByTimeDesc(ctx context.Context, arg sqlc.ListProjectsByTimeDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByTimeDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByTimeDesc indicates an expected call of ListProjectsByTimeDesc.
func (mr *MockQueriesMockRecorder) ListProjectsByTimeDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByTimeDesc", reflect.TypeOf((*MockQueries)(nil).ListProjectsByTimeDesc), ctx, arg)
}

// MockIDatabase is a mock of IDatabase interface.
type MockIDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockIDatabaseMockRecorder
	isgomock struct{}
}

// MockIDatabaseMockRecorder is the mock recorder for MockIDatabase.
type MockIDatabaseMockRecorder struct {
	mock *MockIDatabase
}

// NewMockIDatabase creates a new mock instance.
func NewMockIDatabase(ctrl *gomock.Controller) *MockIDatabase {
	mock := &MockIDatabase{ctrl: ctrl}
	mock.recorder = &MockIDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDatabase) EXPECT() *MockIDatabaseMockRecorder {
	return m.recorder
}

// CountProjects mocks base method.
func (m *MockIDatabase) CountProjects(ctx context.Context, arg sqlc.CountProjectsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProjects", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProjects indicates an expected call of CountProjects.
func (mr *MockIDatabaseMockRecorder) CountProjects(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProjects", reflect.TypeOf((*MockIDatabase)(nil).CountProjects), ctx, arg)
}

// FindProject mocks base method.
func (m *MockIDatabase) FindProject(ctx context.Context, id string) (sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProject", ctx, id)
	ret0, _ := ret[0].(sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProject indicates an expected call of FindProject.
func (mr *MockIDatabaseMockRecorder) FindProject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProject", reflect.TypeOf((*MockIDatabase)(nil).FindProject), ctx, id)
}

// FindProjectDetails mocks base method.
func (m *MockIDatabase) FindProjectDetails(ctx context.Context, projectID string) ([]sqlc.FindProjectDetailsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProjectDetails", ctx, projectID)
	ret0, _ := ret[0].([]sqlc.FindProjectDetailsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProjectDetails indicates an expected call of FindProjectDetails.
func (mr *MockIDatabaseMockRecorder) FindProjectDetails(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProjectDetails", reflect.TypeOf((*MockIDatabase)(nil).FindProjectDetails), ctx, projectID)
}

// ListProjectsByCreatorAsc mocks base method.
func (m *MockIDatabase) ListProjectsByCreatorAsc(ctx context.Context, arg sqlc.ListProjectsByCreatorAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByCreatorAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByCreatorAsc indicates an expected call of ListProjectsByCreatorAsc.
func (mr *MockIDatabaseMockRecorder) ListProjectsByCreatorAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByCreatorAsc", reflect.TypeOf((*MockIDatabase)(nil).ListProjectsByCreatorAsc), ctx, arg)
}

// ListProjectsByCreatorDesc mocks base method.
func (m *MockIDatabase) ListProjectsByCreatorDesc(ctx context.Context, arg sqlc.ListProjectsByCreatorDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByCreatorDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByCreatorDesc indicates an expected call of ListProjectsByCreatorDesc.
func (mr *MockIDatabaseMockRecorder) ListProjectsByCreatorDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByCreatorDesc", reflect.TypeOf((*MockIDatabase)(nil).ListProjectsByCreatorDesc), ctx, arg)
}

// ListProjectsByNameAsc mocks base method.
func (m *MockIDatabase) ListProjectsByNameAsc(ctx context.Context, arg sqlc.ListProjectsByNameAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByNameAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByNameAsc indicates an expected call of ListProjectsByNameAsc.
func (mr *MockIDatabaseMockRecorder) ListProjectsByNameAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByNameAsc", reflect.TypeOf((*MockIDatabase)(nil).ListProjectsByNameAsc), ctx, arg)
}

// ListProjectsByNameDesc mocks base method.
func (m *MockIDatabase) ListProjectsByNameDesc(ctx context.Context, arg sqlc.ListProjectsByNameDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByNameDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByNameDesc indicates an expected call of ListProjectsByNameDesc.
func (mr *MockIDatabaseMockRecorder) ListProjectsByNameDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByNameDesc", reflect.TypeOf((*MockIDatabase)(nil).ListProjectsByNameDesc), ctx, arg)
}

// ListProjectsByTimeAsc mocks base method.
func (m *MockIDatabase) ListProjectsByTimeAsc(ctx context.Context, arg sqlc.ListProjectsByTimeAscParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByTimeAsc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByTimeAsc indicates an expected call of ListProjectsByTimeAsc.
func (mr *MockIDatabaseMockRecorder) ListProjectsByTimeAsc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByTimeAsc", reflect.TypeOf((*MockIDatabase)(nil).ListProjectsByTimeAsc), ctx, arg)
}

// ListProjectsByTimeDesc mocks base method.
func (m *MockIDatabase) ListProjectsByTimeDesc(ctx context.Context, arg sqlc.ListProjectsByTimeDescParams) ([]sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByTimeDesc", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByTimeDesc indicates an expected call of ListProjectsByTimeDesc.
func (mr *MockIDatabaseMockRecorder) ListProjectsByTimeDesc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByTimeDesc", reflect.TypeOf((*MockIDatabase)(nil).ListProjectsByTimeDesc), ctx, arg)
}

// SoftDeleteWinfittsInformation mocks base method.
func (m *MockIDatabase) SoftDeleteWinfittsInformation(ctx context.Context, arg sqlc.SoftDeleteWinfittsInformationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteWinfittsInformation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteWinfittsInformation indicates an expected call of SoftDeleteWinfittsInformation.
func (mr *MockIDatabaseMockRecorder) SoftDeleteWinfittsInformation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteWinfittsInformation", reflect.TypeOf((*MockIDatabase)(nil).SoftDeleteWinfittsInformation), ctx, arg)
}

// UpsertDevices mocks base method.
func (m *MockIDatabase) UpsertDevices(ctx context.Context, arg sqlc.UpsertDevicesParams) (sqlc.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDevices", ctx, arg)
	ret0, _ := ret[0].(sqlc.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertDevices indicates an expected call of UpsertDevices.
func (mr *MockIDatabaseMockRecorder) UpsertDevices(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDevices", reflect.TypeOf((*MockIDatabase)(nil).UpsertDevices), ctx, arg)
}

// UpsertParticipants mocks base method.
func (m *MockIDatabase) UpsertParticipants(ctx context.Context, arg sqlc.UpsertParticipantsParams) (sqlc.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertParticipants", ctx, arg)
	ret0, _ := ret[0].(sqlc.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertParticipants indicates an expected call of UpsertParticipants.
func (mr *MockIDatabaseMockRecorder) UpsertParticipants(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertParticipants", reflect.TypeOf((*MockIDatabase)(nil).UpsertParticipants), ctx, arg)
}

// UpsertProject mocks base method.
func (m *MockIDatabase) UpsertProject(ctx context.Context, arg sqlc.UpsertProjectParams) (sqlc.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertProject", ctx, arg)
	ret0, _ := ret[0].(sqlc.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertProject indicates an expected call of UpsertProject.
func (mr *MockIDatabaseMockRecorder) UpsertProject(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertProject", reflect.TypeOf((*MockIDatabase)(nil).UpsertProject), ctx, arg)
}

// UpsertWinfitts mocks base method.
func (m *MockIDatabase) UpsertWinfitts(ctx context.Context, arg sqlc.UpsertWinfittsParams) (sqlc.Winfitt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWinfitts", ctx, arg)
	ret0, _ := ret[0].(sqlc.Winfitt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertWinfitts indicates an expected call of UpsertWinfitts.
func (mr *MockIDatabaseMockRecorder) UpsertWinfitts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWinfitts", reflect.TypeOf((*MockIDatabase)(nil).UpsertWinfitts), ctx, arg)
}

// UpsertWinfittsDetail mocks base method.
func (m *MockIDatabase) UpsertWinfittsDetail(ctx context.Context, arg sqlc.UpsertWinfittsDetailParams) (sqlc.WinfittsDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWinfittsDetail", ctx, arg)
	ret0, _ := ret[0].(sqlc.WinfittsDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertWinfittsDetail indicates an expected call of UpsertWinfittsDetail.
func (mr *MockIDatabaseMockRecorder) UpsertWinfittsDetail(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWinfittsDetail", reflect.TypeOf((*MockIDatabase)(nil).UpsertWinfittsDetail), ctx, arg)
}

// UpsertWinfittsInformation mocks base method.
func (m *MockIDatabase) UpsertWinfittsInformation(ctx context.Context, arg sqlc.UpsertWinfittsInformationParams) (sqlc.WinfittsInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWinfittsInformation", ctx, arg)
	ret0, _ := ret[0].(sqlc.WinfittsInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertWinfittsInformation indicates an expected call of UpsertWinfittsInformation.
func (mr *MockIDatabaseMockRecorder) UpsertWinfittsInformation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWinfittsInformation", reflect.TypeOf((*MockIDatabase)(nil).UpsertWinfittsInformation), ctx, arg)
}

// WithTx mocks base method.
func (m *MockIDatabase) WithTx(tx *sql.Tx) *sqlc.Queries {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(*sqlc.Queries)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockIDatabaseMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockIDatabase)(nil).WithTx), tx)
}

// MockCommandRepository is a mock of CommandRepository interface.
type MockCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockCommandRepositoryMockRecorder is the mock recorder for MockCommandRepository.
type MockCommandRepositoryMockRecorder struct {
	mock *MockCommandRepository
}

// NewMockCommandRepository creates a new mock instance.
func NewMockCommandRepository(ctrl *gomock.Controller) *MockCommandRepository {
	mock := &MockCommandRepository{ctrl: ctrl}
	mock.recorder = &MockCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandRepository) EXPECT() *MockCommandRepositoryMockRecorder {
	return m.recorder
}

// SoftDeleteWinfittsInformation mocks base method.
func (m *MockCommandRepository) SoftDeleteWinfittsInformation(ctx context.Context, log logger.ILogger, arg sqlc.SoftDeleteWinfittsInformationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteWinfittsInformation", ctx, log, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteWinfittsInformation indicates an expected call of SoftDeleteWinfittsInformation.
func (mr *MockCommandRepositoryMockRecorder) SoftDeleteWinfittsInformation(ctx, log, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteWinfittsInformation", reflect.TypeOf((*MockCommandRepository)(nil).SoftDeleteWinfittsInformation), ctx, log, arg)
}

// UpsertExtractWinfittsDetails mocks base method.
func (m *MockCommandRepository) UpsertExtractWinfittsDetails(ctx context.Context, log logger.ILogger, in models.ProjectSummary, rows []models.WinfittsRawData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertExtractWinfittsDetails", ctx, log, in, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertExtractWinfittsDetails indicates an expected call of UpsertExtractWinfittsDetails.
func (mr *MockCommandRepositoryMockRecorder) UpsertExtractWinfittsDetails(ctx, log, in, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertExtractWinfittsDetails", reflect.TypeOf((*MockCommandRepository)(nil).UpsertExtractWinfittsDetails), ctx, log, in, rows)
}

// MockQueryRepository is a mock of QueryRepository interface.
type MockQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockQueryRepositoryMockRecorder is the mock recorder for MockQueryRepository.
type MockQueryRepositoryMockRecorder struct {
	mock *MockQueryRepository
}

// NewMockQueryRepository creates a new mock instance.
func NewMockQueryRepository(ctrl *gomock.Controller) *MockQueryRepository {
	mock := &MockQueryRepository{ctrl: ctrl}
	mock.recorder = &MockQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryRepository) EXPECT() *MockQueryRepositoryMockRecorder {
	return m.recorder
}

// FindProject mocks base method.
func (m *MockQueryRepository) FindProject(ctx context.Context, log logger.ILogger, id string) (models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProject", ctx, log, id)
	ret0, _ := ret[0].(models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProject indicates an expected call of FindProject.
func (mr *MockQueryRepositoryMockRecorder) FindProject(ctx, log, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProject", reflect.TypeOf((*MockQueryRepository)(nil).FindProject), ctx, log, id)
}

// FindProjectDetails mocks base method.
func (m *MockQueryRepository) FindProjectDetails(ctx context.Context, log logger.ILogger, projectID string) ([]models.ProjectDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProjectDetails", ctx, log, projectID)
	ret0, _ := ret[0].([]models.ProjectDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProjectDetails indicates an expected call of FindProjectDetails.
func (mr *MockQueryRepositoryMockRecorder) FindProjectDetails(ctx, log, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProjectDetails", reflect.TypeOf((*MockQueryRepository)(nil).FindProjectDetails), ctx, log, projectID)
}

// ListProjects mocks base method.
func (m *MockQueryRepository) ListProjects(ctx context.Context, log logger.ILogger, req models.ListProjectRequest) (models.ProjectSummaries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx, log, req)
	ret0, _ := ret[0].(models.ProjectSummaries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockQueryRepositoryMockRecorder) ListProjects(ctx, log, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockQueryRepository)(nil).ListProjects), ctx, log, req)
}

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
	isgomock struct{}
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// FindProject mocks base method.
func (m *MockIRepository) FindProject(ctx context.Context, log logger.ILogger, id string) (models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProject", ctx, log, id)
	ret0, _ := ret[0].(models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProject indicates an expected call of FindProject.
func (mr *MockIRepositoryMockRecorder) FindProject(ctx, log, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProject", reflect.TypeOf((*MockIRepository)(nil).FindProject), ctx, log, id)
}

// FindProjectDetails mocks base method.
func (m *MockIRepository) FindProjectDetails(ctx context.Context, log logger.ILogger, projectID string) ([]models.ProjectDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProjectDetails", ctx, log, projectID)
	ret0, _ := ret[0].([]models.ProjectDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProjectDetails indicates an expected call of FindProjectDetails.
func (mr *MockIRepositoryMockRecorder) FindProjectDetails(ctx, log, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProjectDetails", reflect.TypeOf((*MockIRepository)(nil).FindProjectDetails), ctx, log, projectID)
}

// ListProjects mocks base method.
func (m *MockIRepository) ListProjects(ctx context.Context, log logger.ILogger, req models.ListProjectRequest) (models.ProjectSummaries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx, log, req)
	ret0, _ := ret[0].(models.ProjectSummaries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockIRepositoryMockRecorder) ListProjects(ctx, log, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockIRepository)(nil).ListProjects), ctx, log, req)
}

// SoftDeleteWinfittsInformation mocks base method.
func (m *MockIRepository) SoftDeleteWinfittsInformation(ctx context.Context, log logger.ILogger, arg sqlc.SoftDeleteWinfittsInformationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteWinfittsInformation", ctx, log, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteWinfittsInformation indicates an expected call of SoftDeleteWinfittsInformation.
func (mr *MockIRepositoryMockRecorder) SoftDeleteWinfittsInformation(ctx, log, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteWinfittsInformation", reflect.TypeOf((*MockIRepository)(nil).SoftDeleteWinfittsInformation), ctx, log, arg)
}

// UpsertExtractWinfittsDetails mocks base method.
func (m *MockIRepository) UpsertExtractWinfittsDetails(ctx context.Context, log logger.ILogger, in models.ProjectSummary, rows []models.WinfittsRawData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertExtractWinfittsDetails", ctx, log, in, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertExtractWinfittsDetails indicates an expected call of UpsertExtractWinfittsDetails.
func (mr *MockIRepositoryMockRecorder) UpsertExtractWinfittsDetails(ctx, log, in, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertExtractWinfittsDetails", reflect.TypeOf((*MockIRepository)(nil).UpsertExtractWinfittsDetails), ctx, log, in, rows)
}
