// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/analyzer/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/analyzer/interface.go -destination=mocks/internal_service_analyzer/mock.go -package=mock_internal_service_analyzer IService
//

// Package mock_internal_service_analyzer is a generated GoMock package.
package mock_internal_service_analyzer

import (
	context "context"
	reflect "reflect"

	models "github.com/web4ux/models"
	logger "github.com/web4ux/src/logger"
	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// DeleteOrRestore mocks base method.
func (m *MockIService) DeleteOrRestore(ctx context.Context, log logger.ILogger, informationID string, deleted bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrRestore", ctx, log, informationID, deleted)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrRestore indicates an expected call of DeleteOrRestore.
func (mr *MockIServiceMockRecorder) DeleteOrRestore(ctx, log, informationID, deleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrRestore", reflect.TypeOf((*MockIService)(nil).DeleteOrRestore), ctx, log, informationID, deleted)
}

// GetProjectDetailByID mocks base method.
func (m *MockIService) GetProjectDetailByID(ctx context.Context, log logger.ILogger, projectID string) ([]models.ProjectDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectDetailByID", ctx, log, projectID)
	ret0, _ := ret[0].([]models.ProjectDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectDetailByID indicates an expected call of GetProjectDetailByID.
func (mr *MockIServiceMockRecorder) GetProjectDetailByID(ctx, log, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectDetailByID", reflect.TypeOf((*MockIService)(nil).GetProjectDetailByID), ctx, log, projectID)
}

// ListSummaries mocks base method.
func (m *MockIService) ListSummaries(ctx context.Context, log logger.ILogger, req models.ListSummariesRequest) (models.ProjectSummaries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSummaries", ctx, log, req)
	ret0, _ := ret[0].(models.ProjectSummaries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSummaries indicates an expected call of ListSummaries.
func (mr *MockIServiceMockRecorder) ListSummaries(ctx, log, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSummaries", reflect.TypeOf((*MockIService)(nil).ListSummaries), ctx, log, req)
}
