// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/interface.go
//
// Generated by this command:
//
//	mockgen -source=pkg/interface.go -destination=mocks/pkg/mock.go -package=mock_pkg IProjectFilter
//

// Package mock_pkg is a generated GoMock package.
package mock_pkg

import (
	context "context"
	reflect "reflect"

	htmlparser "github.com/web4ux/src/htmlparser"
	logger "github.com/web4ux/src/logger"
	gomock "go.uber.org/mock/gomock"
)

// MockISyncManager is a mock of ISyncManager interface.
type MockISyncManager struct {
	ctrl     *gomock.Controller
	recorder *MockISyncManagerMockRecorder
	isgomock struct{}
}

// MockISyncManagerMockRecorder is the mock recorder for MockISyncManager.
type MockISyncManagerMockRecorder struct {
	mock *MockISyncManager
}

// NewMockISyncManager creates a new mock instance.
func NewMockISyncManager(ctrl *gomock.Controller) *MockISyncManager {
	mock := &MockISyncManager{ctrl: ctrl}
	mock.recorder = &MockISyncManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISyncManager) EXPECT() *MockISyncManagerMockRecorder {
	return m.recorder
}

// CancelSync mocks base method.
func (m *MockISyncManager) CancelSync() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSync")
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelSync indicates an expected call of CancelSync.
func (mr *MockISyncManagerMockRecorder) CancelSync() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSync", reflect.TypeOf((*MockISyncManager)(nil).CancelSync))
}

// IsRunning mocks base method.
func (m *MockISyncManager) IsRunning() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRunning")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRunning indicates an expected call of IsRunning.
func (mr *MockISyncManagerMockRecorder) IsRunning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRunning", reflect.TypeOf((*MockISyncManager)(nil).IsRunning))
}

// StartSync mocks base method.
func (m *MockISyncManager) StartSync(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSync", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartSync indicates an expected call of StartSync.
func (mr *MockISyncManagerMockRecorder) StartSync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSync", reflect.TypeOf((*MockISyncManager)(nil).StartSync), ctx)
}

// MockIProgressReporter is a mock of IProgressReporter interface.
type MockIProgressReporter struct {
	ctrl     *gomock.Controller
	recorder *MockIProgressReporterMockRecorder
	isgomock struct{}
}

// MockIProgressReporterMockRecorder is the mock recorder for MockIProgressReporter.
type MockIProgressReporterMockRecorder struct {
	mock *MockIProgressReporter
}

// NewMockIProgressReporter creates a new mock instance.
func NewMockIProgressReporter(ctrl *gomock.Controller) *MockIProgressReporter {
	mock := &MockIProgressReporter{ctrl: ctrl}
	mock.recorder = &MockIProgressReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProgressReporter) EXPECT() *MockIProgressReporterMockRecorder {
	return m.recorder
}

// ReportCancellation mocks base method.
func (m *MockIProgressReporter) ReportCancellation(ctx context.Context, log logger.ILogger, projectName string, currentIndex, totalProjects int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportCancellation", ctx, log, projectName, currentIndex, totalProjects)
}

// ReportCancellation indicates an expected call of ReportCancellation.
func (mr *MockIProgressReporterMockRecorder) ReportCancellation(ctx, log, projectName, currentIndex, totalProjects any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportCancellation", reflect.TypeOf((*MockIProgressReporter)(nil).ReportCancellation), ctx, log, projectName, currentIndex, totalProjects)
}

// ReportCompletion mocks base method.
func (m *MockIProgressReporter) ReportCompletion(ctx context.Context, log logger.ILogger, totalProjects int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportCompletion", ctx, log, totalProjects)
}

// ReportCompletion indicates an expected call of ReportCompletion.
func (mr *MockIProgressReporterMockRecorder) ReportCompletion(ctx, log, totalProjects any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportCompletion", reflect.TypeOf((*MockIProgressReporter)(nil).ReportCompletion), ctx, log, totalProjects)
}

// ReportError mocks base method.
func (m *MockIProgressReporter) ReportError(ctx context.Context, log logger.ILogger, errorMessage string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportError", ctx, log, errorMessage)
}

// ReportError indicates an expected call of ReportError.
func (mr *MockIProgressReporterMockRecorder) ReportError(ctx, log, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportError", reflect.TypeOf((*MockIProgressReporter)(nil).ReportError), ctx, log, errorMessage)
}

// ReportProgress mocks base method.
func (m *MockIProgressReporter) ReportProgress(ctx context.Context, log logger.ILogger, projectName string, currentIndex, progress, totalProjects int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportProgress", ctx, log, projectName, currentIndex, progress, totalProjects)
}

// ReportProgress indicates an expected call of ReportProgress.
func (mr *MockIProgressReporterMockRecorder) ReportProgress(ctx, log, projectName, currentIndex, progress, totalProjects any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportProgress", reflect.TypeOf((*MockIProgressReporter)(nil).ReportProgress), ctx, log, projectName, currentIndex, progress, totalProjects)
}

// MockIProjectFilter is a mock of IProjectFilter interface.
type MockIProjectFilter struct {
	ctrl     *gomock.Controller
	recorder *MockIProjectFilterMockRecorder
	isgomock struct{}
}

// MockIProjectFilterMockRecorder is the mock recorder for MockIProjectFilter.
type MockIProjectFilterMockRecorder struct {
	mock *MockIProjectFilter
}

// NewMockIProjectFilter creates a new mock instance.
func NewMockIProjectFilter(ctrl *gomock.Controller) *MockIProjectFilter {
	mock := &MockIProjectFilter{ctrl: ctrl}
	mock.recorder = &MockIProjectFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProjectFilter) EXPECT() *MockIProjectFilterMockRecorder {
	return m.recorder
}

// ShouldProcess mocks base method.
func (m *MockIProjectFilter) ShouldProcess(project htmlparser.ProjectSummary) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldProcess", project)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldProcess indicates an expected call of ShouldProcess.
func (mr *MockIProjectFilterMockRecorder) ShouldProcess(project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldProcess", reflect.TypeOf((*MockIProjectFilter)(nil).ShouldProcess), project)
}

// MockProjectFilter is a mock of ProjectFilter interface.
type MockProjectFilter struct {
	ctrl     *gomock.Controller
	recorder *MockProjectFilterMockRecorder
	isgomock struct{}
}

// MockProjectFilterMockRecorder is the mock recorder for MockProjectFilter.
type MockProjectFilterMockRecorder struct {
	mock *MockProjectFilter
}

// NewMockProjectFilter creates a new mock instance.
func NewMockProjectFilter(ctrl *gomock.Controller) *MockProjectFilter {
	mock := &MockProjectFilter{ctrl: ctrl}
	mock.recorder = &MockProjectFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectFilter) EXPECT() *MockProjectFilterMockRecorder {
	return m.recorder
}

// ShouldProcess mocks base method.
func (m *MockProjectFilter) ShouldProcess(project htmlparser.ProjectSummary) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldProcess", project)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldProcess indicates an expected call of ShouldProcess.
func (mr *MockProjectFilterMockRecorder) ShouldProcess(project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldProcess", reflect.TypeOf((*MockProjectFilter)(nil).ShouldProcess), project)
}
